src_path: '/data/CRIME/one-out/25/src/'
tar_path: '/data/CRIME/one-out/25/tar/'
model_path: '/fslda/models/'
result_path: '/fslda/results/'
csv_path: '/fslda/results/csv/crime/one-out/25/'
indices_path: '/fslda/results/indices/crime/25/'
fig_path: '/fslda/results/figs/crime/25/'
chck_path: '/fslda/chckpoints/'
test_split: 0.20
val_split: 0.25
rand_state: 42
rand_state2: 84
tuning_epochs: 1000
tuning_trials: 400
num_of_frozen_layers: 0
storageN: 'sqlite:///dbs/CRIME.db'
stdy: 'crime'
target_label: 'ViolentCrimesPerPop'
test_samples:
  - 1
  - 3
  - 5
  - 7
  - 9
index_maker:
  module_name: 'index_maker'
  class_name: 'index_maker'
  init_arg: 25
jay_test1:
  module_name: 'jay_test1'
  class_name: 'jay_test1'
  init_arg: 4
train_only:
  module_name: 'train_only'
  class_name: 'train_only'
  init_arg: 100
source_only:
  module_name: 'source_only'
  class_name: 'source_only'
  init_arg: 100
target_only:
  module_name: 'target_only'
  class_name: 'target_only'
  init_arg: 10
target_model:
  module_name: 'target_model'
  class_name: 'target_model'
  init_arg: 10
linear_probing:
  module_name: 'transfer_learning'
  class_name: 'transfer_learning'
  init_arg: 'linear_probing'
  num_of_frozen_layers:
    - 1
    - 2
    - 3
fine_tuning:
  module_name: 'transfer_learning'
  class_name: 'transfer_learning'
  init_arg: 'fine_tuning'
  num_of_frozen_layers:
    - 0
k_regressor:
  module_name: 'k_regressor'
  class_name: 'k_regressor'
  init_arg: 2
random_forrest:
  module_name: 'random_forrest'
  class_name: 'random_forrest'
  init_arg: 100
stacked_model:
  module_name: 'stacked_model'
  class_name: 'stacked_model'
  init_arg: 2
IPT:
  module_name: 'IPT'
  class_name: 'IPT'
  init_arg: 100
  IPT_params:
    neurons: 100
    layers: 6
    lr: 0.01
stacked_ipt:
  module_name: 'stacked_ipt'
  class_name: 'stacked_ipt'
  init_arg: 100
  IPT_params:
    neurons: 100
    layers: 6
    lr: 0.01
TransferIPT:
  init_arg: 'linear_probing'
  module_name: 'TransferIPT'
  class_name: 'TransferIPT'
  IPT_params:
    neurons: 100
    layers: 6
    lr: 0.01
  linear_probing:
    num_of_frozen_layers:
      - 1
      - 2
      - 3
  fine_tuning:
    num_of_frozen_layers:
      - 0
KIPT:
  init_arg: 'fine_tuning'
  module_name: 'KIPT'
  class_name: 'KIPT'
  IPT_params:
    neurons: 100
    layers: 6
    lr: 0.01
  linear_probing:
    num_of_frozen_layers:
      - 1
      - 2
      - 3
  fine_tuning:
    num_of_frozen_layers:
      - 0
res_ipt:
  init_arg: 'fine_tuning'
  module_name: 'res_ipt'
  class_name: 'res_ipt'
  IPT_params:
    neurons: 100
    layers: 6
    lr: 0.01
  linear_probing:
    num_of_frozen_layers:
      - 1
      - 2
      - 3

target_model_params:
  - 500
  - 3
  - 0.05
  - 100
  - 0.8

tasks:
  - transfer_learning
  - transfer_learning
  - value 3

source_model: '/models/crime/one-out/25/crime-model.json'
source_model_weights: '/models/crime/one-out/25/crime-model'
source_model_params: '/fslda/results/txt/Source-model-on-target-crime-parameters.txt'
source_model_prev_weights: '/models/x-crime-SourceModel'
